routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::resource('home','usersController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'name_user', 'email', 'password', 'city', 'profile', 'hobby',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/usersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class usersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('id', 'ASC')->get();

        return view('home')
              ->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);

        return view('userEdit')
            ->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->update($request->all());

        return redirect()->route('home.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/home.blade.php
@extends('principal')

@section('content')
    <br><br>
    <div class="panel panel-default">
        <div class="panel-heading"><center><h4>List Users</h4></center></div>
    </div>
    <table class="table table-striped" style="text-align: center;">
        <thead>
            <th style="text-align: center;">Name</th>
            <th style="text-align: center;">Email</th>
            <th style="text-align: center;">City</th>
            <th style="text-align: center;">Hobby</th>
            <th style="text-align: center;">Edit</th>
        </thead>
        <tbody>
            @foreach ($users as $user)
            <tr>
                <td> {{$user->name}} </td>
                <td> {{$user->email}} </td>
                <td> {{$user->city}} </td>
                <td> 
                    <button class="btn btn-info" data-toggle="modal" data-target="#{{'ModalView'.$user->id}}">
                        View
                    </button>
                </td>
                <td>
                    @if ((auth()->user()->id == $user->id or auth()->user()->profile == "Administrador"))
                    <a href="{{ route('home.edit', $user->id) }}" class="btn btn-warning">
                        Edit
                    </a>
                    @endif
                </td>
            </tr>
            @include('Modal')
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/modal.blade.php
<div class="modal fade" id="{{'ModalView'.$user->id}}" role="dialog">
    <div class="modal-dialog">    
          <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" style="text-align: left">{{ $user->name }}</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
        <div class="modal-body">
            <div align="Center">
                <p>
                    {{ $user->hobby }}
                </p>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
        </div>
    </div>
</div>

resources/views/principal.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    @yield('content')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/userEdit.blade.php
@extends('principal')

@section('content')
    <br><br>
    <div class="panel panel-default">
        <div class="panel-heading"><center><h4>Edit User</h4></center></div>
    </div>
    <div class="panel-body" style="padding-left: 30px; padding-right: 30px">
        <form class="" action="{{ route('home.update', $user->id) }}" method="POST" enctype="multipart/form-data" autocomplete="off">
            {{ method_field('PUT') }}
            {{ csrf_field() }}
            @if ((auth()->user()->profile == "Administrador" ))
            <div class="form-group">
                <label for="InputName">Name</label>
                <input type="text" name="name" class="form-control" placeholder="Name" value="{{ $user->name }}" required>
            </div>
            <div class="form-group">
                <label for="InputName">User</label>
                <input type="text" name="name_user" class="form-control" placeholder="User" value="{{ $user->name_user }}" required>
            </div>
            <div class="form-group">
                <label for="InputEmail1">Correo</label>
                <input type="email" name="email" class="form-control" placeholder="Correo" value="{{ $user->email }}" required maxlength="100">
            </div>
            <div class="form-group">
                <label for="InputLastName1">City</label>
                <input type="text" name="city" class="form-control" placeholder="City" value="{{ $user->city }}" required>
            </div>
            <div class="form-group">
                <label for="InputLastName2">Profile</label>
                <select name="profile" id="profile" class="form-control">
                    <option {{'Usuario' != $user->profile ? '' : 'selected'}} value="Usuario">Usuario</option>
                    <option {{'Administrador' != $user->profile ? '' : 'selected'}} value="Administrador">Administrador</option>
                </select>
            </div>      
            @endif
            <div class="form-group">
                <textarea class="form-control" required autofocus name="hobby" id="hobby" cols="30" rows="10">{{ $user->hobby }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Actualizar</button>
            <a href="{{ route('home.index') }}" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
@endsection